plugins {
    id 'com.android.application'
}

def keystoreB64 = System.getenv('KEYSTORE_B64')

android {
    namespace 'ru.gastroconnect.app'
    compileSdk 34

    defaultConfig {
        applicationId 'ru.gastroconnect.app'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '1.0.2'
    }

    signingConfigs {
        release {
            storeFile file('release.keystore')
            storePassword System.getenv('KEYSTORE_PASSWORD')
            keyAlias System.getenv('KEY_ALIAS')
            keyPassword System.getenv('KEY_PASSWORD')
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (keystoreB64) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}